[book]
authors = ["Konstantin-Dudersky"]
language = "ru"
multilingual = false
src = "src"

[preprocessor.autosummary]
[preprocessor.pagetoc]
[preprocessor.shiftinclude]


[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.pandoc]
optional = true

[output.pandoc.profile.pdf]
output-file = "output.pdf"
to = "typst"

[output.pandoc.profile.pdf.variables]
papersize = "a4"
section-numbering = "1.1.1"


[build]
create-missing = false
